# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    environment:
      REPO_BUILD_DIR: ~/repo/build

    steps:
      # checkout the repository
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      # install aws cli
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version

      - run: aws s3 ls

      # Build react site
      - run: yarn build

      #/home/circleci/repo/build

      #- run:
      #  name: test our generated HTML files
      #  command: 

      - deploy:
          name: deploy to Production AWS s3
          working_directory: $REPO_BUILD_DIR
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $REPO_BUILD_DIR \
              s3://$PRODUCTION_S3_BUCKET_NAME/ --delete
            else
              echo "Not master branch, dry run only"
            fi

      - deploy:
          name: deploy to staging AWS s3
          working_directory: $REPO_BUILD_DIR
          command: |
            if [ "${CIRCLE_BRANCH}" = "staging" ]; then
              aws s3 sync "build" \
              s3://$STAGING_S3_BUCKET_NAME/ --delete
            else
              echo "Not staging branch, dry run only"
            fi