defaults: &defaults
  #working_directory: ./circleci
  docker:
    - image: circleci/node:8
  #working_directory: ~/repo

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - run: # Log the current branch
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
        root: .
        paths:
          - node_modules
        
  testing:
      <<: *defaults
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run: yarn test

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      # Build react site
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build

workflows:
  version: 2
  build_accept_deploy:
  jobs:
      - prepare
      - testing:
          requires:
            - prepare
      - deploy-staging:
          requires:
            - testing
            - build

      - deploy-production:
          type: approval
          requires:
            - testing