version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      # checkout the repository
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test1:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      # run tests!
      - run: yarn test

  staging:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
    - deploy:
          name: deploy to staging AWS s3
          working_directory: ~/repo
          command: |
            if [ "${CIRCLE_BRANCH}" = "staging" ]; then
              aws s3 sync ~/repo/build \
              s3://$STAGING_S3_BUCKET_NAME/ --delete
            else
              echo "Not staging branch, dry run only"
            fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - staging:
          requires:
            - test1
      - deploy:
          requires:
            - staging